# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20180225_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date']},
        ),
    ]
