# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_auto_20180226_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.FileField(blank=True, upload_to='article_images'),
        ),
    ]
